theme: jekyll-theme-cayman
title: Track Wallet
description: Aplikasi Manajemen Keuangan
# Track Wallet merupakan aplikasi yang dibuat dengan tujuan untuk dapat membantu para mahasiswa, Gen Z, dan kaum milenial dalam pengelolaan keuangan. Track Wallet menyediakan berbagai fitur seperti Expense Tracker, Expense Categorization, Data Visualization, dan Alert System yang akan membantu user untuk mengelola keuangannya dengan lebih baik.