name: Automatic Pull Request on Branch Update

on:
  push:
    branches:
      - "475357"
      - "477293"
      - "482759"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
          base: "main" 
          title: Automatic Pull Request - Update from ${{ github.ref }}
          body: |
            This is an automatic pull request created whenever there are updates on the branch.
          commit-message: Automatic commit message
          labels: automatic